Repository LMCache/LMCache, pull requests merged in 2025-09, with the labels that each got.

#1605 [Bugfix] Fix gds loading bytes comparison error
  lmcache/v1/storage_backend/gds_backend.py
Labels: full

#1588 Update vLLM options for MLA test
  .buildkite/configs/lmcache_configs/local_cpu_mla.yaml
  .buildkite/configs/local_cpu_mla.yaml
  .buildkite/scripts/pick-free-gpu.sh
  .buildkite/scripts/vllm-integration-tests.sh
Labels: full

#1603 support tmp path in FSConnector
  lmcache/v1/storage_backend/connector/fs_adapter.py
  lmcache/v1/storage_backend/connector/fs_connector.py
Labels: fs_connector

#1631 [Core] Fix NixlStorageBackend import
  lmcache/v1/storage_backend/nixl_storage_backend.py
Labels: bug, chore
