Repository LMCache/LMCache, pull requests merged in 2025-05, with the labels that each got.

#614 [Doc] Update README.md to add DeepWiki badge and clean up spacing
  README.md
Labels: documentation

#645 [Bugfix] Fix GPU buffer allocator
  lmcache/experimental/gpu_connector.py
  lmcache/experimental/memory_management.py
Labels: E2E

#728 [Refactor]: Remove duplicate code from setup.py
  setup.py
Labels: Refactoring
