Repository LMCache/LMCache, pull requests merged in 2025-07, with the labels that each got.

#930 [Test]: Add integration testing for LMCache integration with vLLM
  .buildkite/vllm-integration-tests.yml
  scripts/vllm-integration-tests.sh
Labels: integration_testing

#997 Simple Adapt KV Connector
  lmcache/integration/vllm/vllm_v1_adapter.py
Labels: E2E

#1017 [CI]: Add stale issue bot
  .github/workflows/stale_bot.yml
Labels: chore

#1005 [Doc]: Small improvements to contributing guide
  docs/source/developer_guide/contributing.rst
Labels: documentation

#1059 [Refactor]: Remove unnecessary build package dependency
  pyproject.toml
  requirements/build.txt
Labels: Refactoring

#1098 [ci]: Refactor docs workflow
  .github/workflows/build_doc.yml
Labels: Refactoring, ci

#1103 [fix]: Enable container access for score card and PyPI workflow
  .github/workflows/publish.yml
  .github/workflows/scorecard.yml
Labels: bug, ci

#1126 [CI/Build] Check end to end results
  .buildkite/scripts/end-to-end-test.sh
Labels: E2E
